version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: opencart
      MYSQL_USER: opencart
      MYSQL_PASSWORD: opencart
    ports:
      - "3306:3306"

  opencart:
    image: opencart/opencart:latest
    depends_on:
      - db
    environment:
      DB_HOSTNAME: db
      DB_USERNAME: opencart
      DB_PASSWORD: opencart
      DB_DATABASE: opencart
    ports:
      - "8080:80"

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"